version: "3.9"
services:
  neumann-api:
    build:
      context: .
    ports:
      - ${NEUMANN_API_PORT}:${NEUMANN_API_PORT}
    volumes:
      - ./:/usr/src/neumann_api
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
