version: "3.9"
services:
  neumann-api:
    image: brunofagner/neumann_api:v1
    ports:
      - 80:80
    volumes:
      - ./:/usr/src/neumann_api
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: carlos
      MONGO_INITDB_ROOT_PASSWORD: 12345678
